# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_luttich_germanapproach_1", 202, group = 2),
  spawnPoint("CP_16_luttich_germanapproach_2", 202, group = 2),
  spawnPoint("CP_16_luttich_germanapproach_3", 202),
  spawnPoint("CP_16_luttich_germanapproach_4", 202, group = 1),
  spawnPoint("CP_16_luttich_germanapproach_5", 202, group = 1),
  spawnPoint("CP_16_luttich_germanapproach_6", 202),
  spawnPoint("CP_16_luttich_usapproach_1", 203),
  spawnPoint("CP_16_luttich_usapproach_3", 203, group = 2),
  spawnPoint("CP_16_luttich_usapproach_4", 203, group = 2),
  spawnPoint("CP_16_luttich_usapproach_6", 203),
  spawnPoint("CP_16_luttich_usapproach_7", 203, group = 2),
  spawnPoint("CP_16_luttich_usapproach_8", 203, group = 1),
  spawnPoint("CP_16_luttich_usapproach_7_0", 203, group = 1),
  spawnPoint("CP_16_luttich_germanapproach_7", 202, group = 1),
]
