# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("conq_16_Mont_4", 201, group = 1),
  spawnPoint("conq_16_Mont_5", 201, group = 1),
  spawnPoint("conq_16_Neffe_1", 202),
  spawnPoint("conq_16_Neffe_2", 202),
  spawnPoint("conq_16_Neffe_3", 202, group = 1),
  spawnPoint("conq_16_Neffe_4", 202, group = 1),
  spawnPoint("conq_64_Bridge_1", 203),
  spawnPoint("conq_64_Bridge_2", 203),
  spawnPoint("conq_64_Bridge_3", 203, group = 1),
  spawnPoint("conq_64_Bridge_4", 203, group = 1),
  spawnPoint("conq_16_Rail_1", 204),
  spawnPoint("conq_16_Rail_2", 204),
  spawnPoint("conq_16_Rail_3", 204, group = 1),
  spawnPoint("conq_16_Rail_4", 204),
]
