# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("cp_16_little_saturn_ravenna_division_1", 302),
  spawnPoint("cp_16_little_saturn_ravenna_division_2", 302),
  spawnPoint("cp_16_little_saturn_ravenna_division_3", 302),
  spawnPoint("cp_16_little_saturn_ravenna_division_4", 302),
  spawnPoint("cp_16_little_saturn_ravenna_division_5", 302),
  spawnPoint("cp_16_little_saturn_1st_guards_army_1", 303),
  spawnPoint("cp_16_little_saturn_1st_guards_army_2", 303),
  spawnPoint("cp_16_little_saturn_1st_guards_army_3", 303),
  spawnPoint("cp_16_little_saturn_1st_guards_army_4", 303),
  spawnPoint("cp_16_little_saturn_1st_guards_army_5", 303),
]
