# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_GW_Orchard_1_0", 201),
  spawnPoint("CP_16_GW_Orchard_2_0", 201),
  spawnPoint("CP_16_GW_Orchard_3_0", 201),
  spawnPoint("CP_16_GW_Orchard_4_0", 201),
  spawnPoint("CP_16_GW_Church_1", 202),
  spawnPoint("CP_16_GW_Church_2", 202),
  spawnPoint("CP_16_GW_Church_3", 202),
  spawnPoint("CP_16_GW_Church_4", 202),
  spawnPoint("CP_16_GW_Church_5", 202),
  spawnPoint("CP_16_GW_FarmSouth_2", 203),
  spawnPoint("CP_16_GW_FarmSouth_2_0", 203),
  spawnPoint("CP_16_GW_FarmSouth_3", 203),
  spawnPoint("CP_16_GW_FarmSouth_4", 203),
  spawnPoint("CP_16_GW_Station_1", 204),
  spawnPoint("CP_16_GW_Station_2", 204),
  spawnPoint("CP_16_GW_Station_3", 204),
  spawnPoint("CP_16_GW_Station_4", 204),
  spawnPoint("CP_16_GW_FarmWest_1", 205),
  spawnPoint("CP_16_GW_FarmWest_2", 205),
  spawnPoint("CP_16_GW_FarmWest_3", 205),
]
