# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_vo_us_base_1", 203),
  spawnPoint("CP_16_vo_de_base_1", 204),
  spawnPoint("CP_16_vo_church1_Allies_1", 201),
  spawnPoint("CP_16_vo_church1_Allies_2", 201),
  spawnPoint("CP_16_vo_church1_Axis_1", 201),
  spawnPoint("CP_16_vo_church1_Axis_2", 201),
  spawnPoint("CP_16_vo_church1_Axis_3", 201),
  spawnPoint("CP_16_vo_church1_Axis_4", 201),
  spawnPoint("CP_16_vo_church1_Allies_3", 201),
  spawnPoint("CP_16_vo_church1_Allies_4", 201),
  spawnPoint("CP_16_vo_us_base_2", 203),
  spawnPoint("CP_16_vo_us_base_3", 203),
  spawnPoint("CP_16_vo_de_base_3", 204),
  spawnPoint("CP_16_vo_de_base_4", 204),
  spawnPoint("CP_16_vo_church1_1", 201),
]
