# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_omaha_wn71_1", 202),
  spawnPoint("CP_16_omaha_wn71_2", 202),
  spawnPoint("CP_16_omaha_wn71_3", 202),
  spawnPoint("CP_16_omaha_wn71_4", 202),
  spawnPoint("CP_16_omaha_wn71_5", 202),
  spawnPoint("CP_16_omaha_wn73_1", 203),
  spawnPoint("CP_16_omaha_wn73_2", 203),
  spawnPoint("CP_16_omaha_wn73_3", 203),
  spawnPoint("CP_16_omaha_wn73_4", 203),
]
