# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_la_fiere_alliesspawn_allies1", 303),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies2", 303),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies3", 303),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies4", 303),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies5", 303),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies6", 303, group = 1),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies7", 303, group = 1),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies8", 303, group = 1),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies9", 303, group = 1),
  spawnPoint("CP_16_la_fiere_alliesspawn_allies10", 303, group = 1),
  spawnPoint("CP_16_la_fiere_axisspawn_axis1", 301),
  spawnPoint("CP_16_la_fiere_axisspawn_axis2", 301),
  spawnPoint("CP_16_la_fiere_axisspawn_axis3", 301),
  spawnPoint("CP_16_la_fiere_axisspawn_axis4", 301),
  spawnPoint("CP_16_la_fiere_axisspawn_axis5", 301),
  spawnPoint("CP_16_la_fiere_axisspawn_axis6", 301, group = 1),
  spawnPoint("CP_16_la_fiere_axisspawn_axis7", 301, group = 1),
  spawnPoint("CP_16_la_fiere_axisspawn_axis8", 301, group = 1),
  spawnPoint("CP_16_la_fiere_axisspawn_axis9", 301, group = 1),
  spawnPoint("CP_16_la_fiere_axisspawn_axis10", 301, group = 1),
]
