# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_stmarie_rue_joly_Ger1", 302),
  spawnPoint("CP_16_stmarie_rue_joly_Ger2", 302),
  spawnPoint("CP_16_stmarie_rue_joly_Ger3", 302),
  spawnPoint("CP_16_stmarie_rue_joly_Ger4", 302),
  spawnPoint("CP_16_stmarie_rue_joly_Ger5", 302, group = 1),
  spawnPoint("CP_16_stmarie_rue_joly_Ger6", 302, group = 1),
  spawnPoint("CP_16_stmarie_rue_joly_Ger7", 302, group = 1),
  spawnPoint("CP_16_stmarie_rue_thouays_Us1", 303),
  spawnPoint("CP_16_stmarie_rue_thouays_Us2", 303),
  spawnPoint("CP_16_stmarie_rue_thouays_Us3", 303),
  spawnPoint("CP_16_stmarie_rue_thouays_Us4", 303),
  spawnPoint("CP_16_stmarie_rue_thouays_Us5", 303, group = 2),
  spawnPoint("CP_16_stmarie_rue_thouays_Us6", 303, group = 2),
  spawnPoint("CP_16_stmarie_rue_thouays_Us7", 303, group = 2),
]
