# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_64_stmarie_USforward_1", 2),
  spawnPoint("CP_64_stmarie_USforward_2", 2),
  spawnPoint("CP_64_stmarie_USforward_3", 2),
  spawnPoint("CP_64_stmarie_USforward_4", 2),
  spawnPoint("CP_64_stmarie_USforward_5", 2),
  spawnPoint("CP_64_stmarie_USforward_6", 2),
]
