# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_meb_alliedspawns_1", 301),
  spawnPoint("CP_16_meb_alliedspawns_2", 301),
  spawnPoint("CP_16_meb_alliedspawns_3", 301),
  spawnPoint("CP_16_meb_alliedspawns_4", 301),
  spawnPoint("CP_16_meb_alliedspawns_5", 301),
  spawnPoint("CP_16_meb_alliedspawns_6", 301),
  spawnPoint("CP_16_meb_alliedspawns_7", 301),
  spawnPoint("CP_16_meb_alliedspawns_8", 301),
  spawnPoint("CP_16_meb_alliedspawns_9", 301),
  spawnPoint("CP_16_meb_alliedspawns_10", 301),
  spawnPoint("CP_16_meb_axisspawns_1", 302),
  spawnPoint("CP_16_meb_axisspawns_2", 302),
  spawnPoint("CP_16_meb_axisspawns_3", 302),
  spawnPoint("CP_16_meb_axisspawns_4", 302),
  spawnPoint("CP_16_meb_axisspawns_5", 302),
  spawnPoint("CP_16_meb_axisspawns_6", 302),
  spawnPoint("CP_16_meb_axisspawns_7", 302),
  spawnPoint("CP_16_meb_axisspawns_8", 302),
  spawnPoint("CP_16_meb_axisspawns_9", 302),
  spawnPoint("CP_16_meb_axisspawns_10", 302),
]
