# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("RU_Airstrip_1", 1),
  spawnPoint("RU_Airstrip_2", 1),
  spawnPoint("RU_Airstrip_3", 1),
  spawnPoint("RU_Airstrip_4", 1),
  spawnPoint("RU_Airstrip_5", 1),
  spawnPoint("RU_Airstrip_6", 1),
  spawnPoint("RU_Airstrip_7", 1),
]
