# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_hurtgen_axismain_1", 301),
  spawnPoint("CP_16_hurtgen_axismain_2", 301),
  spawnPoint("CP_16_hurtgen_axismain_3", 301),
  spawnPoint("CP_16_hurtgen_axismain_4", 301),
  spawnPoint("CP_16_hurtgen_axismain_5", 301),
  spawnPoint("CP_16_hurtgen_axismain_6", 301),
  spawnPoint("CP_16_hurtgen_axismain_7", 301),
  spawnPoint("CP_16_hurtgen_axismain_8", 301),
  spawnPoint("CP_16_hurtgen_axismain_9", 301),
  spawnPoint("CP_16_hurtgen_alliedmain_1", 302),
  spawnPoint("CP_16_hurtgen_alliedmain_2", 302),
  spawnPoint("CP_16_hurtgen_alliedmain_3", 302),
  spawnPoint("CP_16_hurtgen_alliedmain_4", 302),
  spawnPoint("CP_16_hurtgen_alliedmain_5", 302),
  spawnPoint("CP_16_hurtgen_alliedmain_6", 302),
  spawnPoint("CP_16_hurtgen_alliedmain_7", 302),
]
