# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_Gazala_GermanAdvance_1", 101),
  spawnPoint("CP_16_Gazala_GermanAdvance_2", 101),
  spawnPoint("CP_16_Gazala_GermanAdvance_3", 101),
  spawnPoint("CP_16_Gazala_GermanAdvance_4", 101),
  spawnPoint("CP_16_Gazala_GermanAdvance_5", 101),
  spawnPoint("CP_16_Gazala_GermanAdvance_7", 101),
  spawnPoint("CP_16_Gazala_BritishAdvance_1", 104),
  spawnPoint("CP_16_Gazala_BritishAdvance_2", 104),
  spawnPoint("CP_16_Gazala_BritishAdvance_3", 104),
  spawnPoint("CP_16_Gazala_BritishAdvance_4", 104),
  spawnPoint("CP_16_Gazala_BritishAdvance_5", 104),
  spawnPoint("CP_16_Gazala_BritishAdvance_6", 104),
  spawnPoint("CP_16_Gazala_BritishAdvance_7", 104),
  spawnPoint("CP_16_Gazala_BritishAdvance_8", 104),
  spawnPoint("CP_16_Gazala_GermanAdvance_8", 101),
  spawnPoint("CP_16_Gazala_GermanAdvance_9", 101),
]
