# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_32_Ramelle_Ger_1", 302),
  spawnPoint("CP_32_Ramelle_Ger_2", 302),
  spawnPoint("CP_32_Ramelle_Ger_3", 302),
  spawnPoint("CP_32_Ramelle_Ger_4", 302),
  spawnPoint("CP_32_Ramelle_Ger_5", 302),
  spawnPoint("CP_32_Ramelle_Ger_6", 302, group = 1),
  spawnPoint("CP_32_Ramelle_Ger_7", 302, group = 1),
  spawnPoint("CP_32_Ramelle_Ger_8", 302, group = 1),
  spawnPoint("CP_32_Ramelle_Ger_9", 302, group = 1),
  spawnPoint("CP_32_Ramelle_Ger_10", 302, group = 1),
  spawnPoint("CP_32_Ramelle_US_1", 301),
  spawnPoint("CP_32_Ramelle_US_2", 301),
  spawnPoint("CP_32_Ramelle_US_3", 301),
  spawnPoint("CP_32_Ramelle_US_4", 301),
  spawnPoint("CP_32_Ramelle_US_5", 301),
  spawnPoint("CP_32_Ramelle_US_6", 301),
  spawnPoint("CP_32_Ramelle_US_7", 301),
  spawnPoint("CP_32_Ramelle_US_8", 301),
]
