# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_8_seelow_russianmain_1", 501, group = 1),
  spawnPoint("CP_8_seelow_russianmain_2", 501),
  spawnPoint("CP_8_seelow_russianmain_3", 501, group = 1),
  spawnPoint("CP_8_seelow_russianmain_4", 501, group = 1),
  spawnPoint("CP_8_seelow_russianmain_5", 501),
  spawnPoint("CP_8_seelow_russianmain_6", 501),
  spawnPoint("CP_8_seelow_russianmain_8", 501),
  spawnPoint("CP_8_seelow_russianmain_9", 501, group = 1),
  spawnPoint("CP_8_seelow_russianmain_10", 501, group = 1),
  spawnPoint("CP_8_seelow_germanmain_1", 502),
  spawnPoint("CP_8_seelow_germanmain_2", 502),
  spawnPoint("CP_8_seelow_germanmain_3", 502),
  spawnPoint("CP_8_seelow_germanmain_4", 502, group = 1),
  spawnPoint("CP_8_seelow_germanmain_5", 502, group = 1),
  spawnPoint("CP_8_seelow_germanmain_6", 502, group = 2),
  spawnPoint("CP_8_seelow_germanmain_7", 502, group = 2),
  spawnPoint("CP_8_seelow_germanmain_8", 502, group = 2),
  spawnPoint("CP_8_seelow_germanmain_9", 502, group = 1),
  spawnPoint("CP_8_seelow_germanmain_10", 502, group = 1),
]
