layers = [16, 32, 64]
intervals = [[16, 31], [32, 64], [65, 100]]
front = ["west_late"]
date = "1944-06-06"
teams = ["Germany", "Great Britain"]
version_added = "2.46"
authors = ["Beregil", "Schism"]
