# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_32_La_Horgne_Church_place_1", 301),
  spawnPoint("CP_32_La_Horgne_Church_place_2", 301),
  spawnPoint("CP_32_La_Horgne_Church_place_3", 301),
  spawnPoint("CP_32_La_Horgne_Cemetery_1", 302),
  spawnPoint("CP_32_La_Horgne_Cemetery_2", 302),
  spawnPoint("CP_32_La_Horgne_Cemetery_3", 302),
  spawnPoint("CP_32_La_Horgne_Perotin_Farm_1_0", 303),
  spawnPoint("CP_32_La_Horgne_Perotin_Farm_2_0", 303),
  spawnPoint("CP_32_La_Horgne_Perotin_Farm_3_0", 303),
  spawnPoint("CP_32_La_Horgne_La_Tour_Farm_1", 304),
  spawnPoint("CP_32_La_Horgne_La_Tour_Farm_2", 304),
  spawnPoint("CP_32_La_Horgne_La_Tour_Farm_3", 304),
  spawnPoint("CP_32_La_Horgne_Voirin_Farm_1", 305),
  spawnPoint("CP_32_La_Horgne_Voirin_Farm_2", 305),
  spawnPoint("CP_32_La_Horgne_Voirin_Farm_3", 305),
]
