# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_pogostje_shala_allies1_0", 302),
  spawnPoint("CP_16_pogostje_kuchenschneise_axis1_0", 303),
  spawnPoint("CP_16_pogostje_kuchenschneise_2", 303),
  spawnPoint("CP_16_pogostje_kuchenschneise_3", 303),
  spawnPoint("CP_16_pogostje_kuchenschneise_4", 303, group = 1),
  spawnPoint("CP_16_pogostje_kuchenschneise_5", 303, group = 1),
  spawnPoint("CP_16_pogostje_kuchenschneise_6", 303, group = 1),
  spawnPoint("CP_16_pogostje_kuchenschneise_7", 303, group = 3),
  spawnPoint("CP_16_pogostje_kuchenschneise_8", 303, group = 3),
  spawnPoint("CP_16_pogostje_kuchenschneise_9", 303, group = 3),
  spawnPoint("CP_16_pogostje_shala_2", 302),
  spawnPoint("CP_16_pogostje_shala_3", 302),
  spawnPoint("CP_16_pogostje_shala_4", 302, group = 3),
  spawnPoint("CP_16_pogostje_shala_5", 302, group = 3),
  spawnPoint("CP_16_pogostje_shala_6", 302, group = 3),
  spawnPoint("CP_16_pogostje_shala_7", 302, group = 1),
  spawnPoint("CP_16_pogostje_shala_8", 302, group = 1),
  spawnPoint("CP_16_pogostje_shala_9", 302, group = 1),
]
