# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_stonne_7eCompagnie_1", 202),
  spawnPoint("CP_16_stonne_7eCompagnie_2", 202),
  spawnPoint("CP_16_stonne_7eCompagnie_3", 202),
  spawnPoint("CP_16_stonne_7eCompagnie_4", 202),
  spawnPoint("CP_16_stonne_7eCompagnie_5", 202),
  spawnPoint("CP_16_stonne_7eCompagnie_6", 202),
  spawnPoint("CP_16_stonne_79eRI_1", 203),
  spawnPoint("CP_16_stonne_79eRI_2", 203),
  spawnPoint("CP_16_stonne_79eRI_3", 203),
  spawnPoint("CP_16_stonne_79eRI_4", 203),
  spawnPoint("CP_16_stonne_79eRI_5", 203),
  spawnPoint("CP_16_stonne_79eRI_6", 203),
]
