# -*- coding: utf-8 -*-
# pylint: disable=C0301,C0114,C0103,C0302,R1735
# vim:set ts=4 sts=4 sw=4 et syntax=python:
"""vehicle properties, for artillery, deployables, etc
"""

parachutes = (
    "rz20chute",
    "x9chute",
)

# NOTE: when setting max_elevation/min_elevation,
# DIRECTLY copy it from the .tweak file -- don't apply the sign flip here
# e.g. 25pdr:
#   ObjectTemplate.setMinRotation 0/-24/0
#   ObjectTemplate.setMaxRotation 0/20/0
# -> max_elevation=20, min_elevation=-24
artillery_info = {
    "25pdr": dict(
        barrel="25pdr_barrel",
        camera="25pdr_remotecam_holder",
        velocity=494.0,
        gravitymod=10.0,
        elevation_offset=-16.3974,
        static=True,
        min_elevation=-18,
        max_elevation=20,
    ),
    "25pdr_ai": dict(
        barrel="25pdr_barrel",
        camera="25pdr_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-16.3974,
        static=True,
        min_elevation=-24,
        max_elevation=20,
    ),
    "25pdr_mkiv": dict(
        barrel="25pdr_mkiv_barrel",
        camera="25pdr_mkiv_remotecam_holder",
        velocity=556.0,
        gravitymod=10.0,
        elevation_offset=-16.3974,
        static=True,
        min_elevation=-18,
        max_elevation=20,
    ),
    "25pdr_mkiv_ai": dict(
        barrel="25pdr_mkiv_barrel",
        camera="25pdr_mkiv_remotecam_holder",
        velocity=540.0,
        gravitymod=10.0,
        elevation_offset=-16.3974,
        static=True,
        min_elevation=-24,
        max_elevation=20,
    ),
    "81krh36": dict(
        barrel="81krh36_barrel",
        camera="81krh36_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81krh36_ai": dict(
        barrel="81krh36_barrel",
        camera="81krh36_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81krh36_deployed": dict(
        barrel="81krh36_barrel",
        camera="81krh36_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "3inchmortar": dict(
        barrel="3inchmortar_mortarfirearm",
        camera="3inchmortar_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-50.25,
        parabolic=True,
        min_elevation=-37,
        max_elevation=20,
    ),
    "3inchmortar_ai": dict(
        barrel="3inchmortar_mortarfirearm",
        camera="3inchmortar_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-50.25,
        parabolic=True,
        min_elevation=-37,
        max_elevation=20,
    ),
    "3inchmortar_deployed": dict(
        barrel="3inchmortar_mortarfirearm",
        camera="3inchmortar_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-50.25,
        parabolic=True,
        min_elevation=-37,
        max_elevation=20,
    ),
    "75mdle1897": dict(
        barrel="75mdle1897_cannon",
        camera="75mdle1897_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.25,
        static=True,
        min_elevation=-10,
        max_elevation=15,
    ),
    "75mdle1897_wood": dict(
        barrel="75mdle1897_wood_cannon",
        camera="75mdle1897_wood_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.25,
        static=True,
        min_elevation=-17,
        max_elevation=8,
    ),
    "81mm_mortar_fr_2730": dict(
        barrel="81mm_mortar_fr_2730_mortarfirearm",
        camera="81mm_mortar_fr_2730_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_fr_2730_ai": dict(
        barrel="81mm_mortar_fr_2730_mortarfirearm",
        camera="81mm_mortar_fr_2730_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_fr_2730_deployed": dict(
        barrel="81mm_mortar_fr_2730_mortarfirearm",
        camera="81mm_mortar_fr_2730_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_no_m35": dict(
        barrel="81mm_mortar_no_m35_mortarfirearm",
        camera="81mm_mortar_no_m35_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_no_m35_ai": dict(
        barrel="81mm_mortar_no_m35_mortarfirearm",
        camera="81mm_mortar_no_m35_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_no_m35_deployed": dict(
        barrel="81mm_mortar_no_m35_mortarfirearm",
        camera="81mm_mortar_no_m35_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_m1": dict(
        barrel="81mm_mortar_m1_mortarfirearm",
        camera="81mm_mortar_m1_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_m1_ai": dict(
        barrel="81mm_mortar_m1_mortarfirearm",
        camera="81mm_mortar_m1_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "81mm_mortar_m1_deployed": dict(
        barrel="81mm_mortar_m1_mortarfirearm",
        camera="81mm_mortar_m1_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-10,
        max_elevation=44,
    ),
    "bishop": dict(
        barrel="bishop_Barrel",
        camera="bishop_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.5,
        static=False,
        min_elevation=-9,
        max_elevation=4,
    ),
    "britcommradio": dict(
        barrel="britcommradio_gun",
        camera="britcommradio_remotecam_holder",
        velocity=1000.0,
        gravitymod=1.0,
        elevation_offset=0.0,
        static=True,
    ),
    "gercommradio": dict(
        barrel="gercommradio_gun",
        camera="gercommradio_remotecam_holder",
        velocity=1000.0,
        gravitymod=1.0,
        elevation_offset=0.0,
        static=True,
    ),
    "gpf_155mm": dict(
        barrel="GPF_155mm_Barrel",
        camera="gpf_155mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.25,
        static=True,
        min_elevation=-20,
        max_elevation=15,
    ),
    "lefh18": dict(
        barrel="lefh18_gun",
        camera="lefh18_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.25,
        static=True,
        min_elevation=-20,
        max_elevation=15,
    ),
    "lefh18_ai": dict(
        barrel="lefh18_gun",
        camera="lefh18_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.25,
        static=True,
        min_elevation=-20,
        max_elevation=15,
    ),
    "lefh18_france": dict(
        barrel="lefh18_france_gun",
        camera="lefh18_france_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.25,
        static=True,
        min_elevation=-20,
        max_elevation=15,
    ),
    "lefh18_france_ai": dict(
        barrel="lefh18_france_gun",
        camera="lefh18_france_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.25,
        static=True,
        min_elevation=-20,
        max_elevation=15,
    ),
    "m2a1_howitzer_105mm": dict(
        barrel="m2a1_howitzer_105mm_barrel",
        camera="105mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-13.9,
        static=True,
        min_elevation=-21,
        max_elevation=16,
    ),
    "m2a1_howitzer_105mm_ai": dict(
        barrel="m2a1_howitzer_105mm_barrel",
        camera="105mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-13.9,
        static=True,
        min_elevation=-21,
        max_elevation=16,
    ),
    "m2a1_howitzer_105mm_win": dict(
        barrel="m2a1_howitzer_105mm_win_barrel",
        camera="105mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-13.9,
        static=True,
        min_elevation=-21,
        max_elevation=16,
    ),
    "m2a1_howitzer_105mm_win_ai": dict(
        barrel="m2a1_howitzer_105mm_win_barrel",
        camera="105mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-13.9,
        static=True,
        min_elevation=-21,
        max_elevation=16,
    ),
    "m30_122mm": dict(
        barrel="m30_122mm_gun",
        camera="m30_122mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.6,
        static=True,
        min_elevation=-20,
        max_elevation=7.5,
    ),
    "m30_122mm_ai": dict(
        barrel="m30_122mm_gun",
        camera="m30_122mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.6,
        static=True,
        min_elevation=-20,
        max_elevation=7.5,
    ),
    "m30_122mm_fin": dict(
        barrel="m30_122mm_fin_gun",
        camera="m30_122mm_fin_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.6,
        static=True,
        min_elevation=-20,
        max_elevation=7.5,
    ),
    "m30_122mm_fin_ai": dict(
        barrel="m30_122mm_fin_gun",
        camera="m30_122mm_fin_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.6,
        static=True,
        min_elevation=-20,
        max_elevation=7.5,
    ),
    "m4a3_rocket": dict(
        barrel="m4a3_rocket_barrel",
        camera="m4a3_rocket_remotecam_holder",
        velocity=853.0,
        gravitymod=1.5,
        elevation_offset=-0.5,
        static=False,
    ),
    "m7_priest": dict(
        barrel="m7_priest_barrel",
        camera="m7_priest_remotecam_holder",
        velocity=480.0,
        gravitymod=10,
        elevation_offset=-0.7,
        static=False,
        min_elevation=-21,
        max_elevation=16,
    ),
    "nebelwerfer": dict(
        barrel="nebelwerfer_barrel_he",
        camera="nebelwerfer_remotecam_holder",
        velocity=195.0,
        gravitymod=1.8,
        elevation_offset=-0.5,
        static=True,
        min_elevation=-44,
        max_elevation=25,
    ),
    "nebelwerfer_ai": dict(
        barrel="nebelwerfer_barrel_he",
        camera="nebelwerfer_remotecam_holder",
        velocity=195.0,
        gravitymod=1.8,
        elevation_offset=-0.5,
        static=True,
        min_elevation=-20,
        max_elevation=25,
    ),
    "nebelwerfer_ard": dict(
        barrel="nebelwerfer_ard_barrel_he",
        camera="nebelwerfer_ard_remotecam_holder",
        velocity=195.0,
        gravitymod=1.8,
        elevation_offset=-0.5,
        static=True,
        min_elevation=-44,
        max_elevation=25,
    ),
    "nebelwerfer_pan": dict(
        barrel="nebelwerfer_pan_barrel_he",
        camera="nebelwerfer_pan_remotecam_holder",
        velocity=195.0,
        gravitymod=1.8,
        elevation_offset=-0.5,
        static=True,
        min_elevation=-44,
        max_elevation=25,
    ),
    "nebelwerfer_win": dict(
        barrel="nebelwerfer_win_barrel_he",
        camera="nebelwerfer_win_remotecam_holder",
        velocity=195.0,
        gravitymod=1.8,
        elevation_offset=-0.5,
        static=True,
        min_elevation=-44,
        max_elevation=25,
    ),
    "renault_ue_zu_fuss": dict(
        barrel="renault_ue_wurfrahmen_gun",
        camera="renault_ue_wurfrahmen_remotecam_holder",
        velocity=150.0,
        gravitymod=1.8,
        elevation_offset=-16.5,
        static=False,
        min_elevation=-15,
        max_elevation=0,
    ),
    "ru_mortar120mm": dict(
        barrel="ru_mortar120mm_mortarfirearm",
        camera="ru_mortar120mm_remotecam_holder",
        velocity=254.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-12,
        max_elevation=44,
    ),
    "ru_mortar82mm": dict(
        barrel="ru_mortar82mm_mortarfirearm",
        camera="ru_mortar82mm_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-50.25,
        parabolic=True,
        min_elevation=-37,
        max_elevation=20,
    ),
    "ru_mortar82mm_deployed": dict(
        barrel="ru_mortar82mm_mortarfirearm",
        camera="ru_mortar82mm_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-50.25,
        parabolic=True,
        min_elevation=-37,
        max_elevation=20,
    ),
    "schneider_1913": dict(
        barrel="schneider_1913_gun",
        camera="schneider_1913_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.5,
        static=True,
        min_elevation=-25,
        max_elevation=2.5,
    ),
    "schneider_1913_ai": dict(
        barrel="schneider_1913_gun",
        camera="schneider_1913_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.5,
        static=True,
        min_elevation=-20,
        max_elevation=15,
    ),
    "sgwr34": dict(
        barrel="sgwr34_mortarfirearm",
        camera="sgwr34_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-12,
        max_elevation=44,
    ),
    "sgwr34_ai": dict(
        barrel="sgwr34_mortarfirearm",
        azimuth="sgwr34_remotecam_azi_req",
        elevation="sgwr34_remotecam_elev_req",
        camera="sgwr34_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        indicator="sgwr34_remotecam_targetind",
        parabolic=True,
        min_elevation=-12,
        max_elevation=44,
    ),
    "sgwr34_deployed": dict(
        barrel="sgwr34_mortarfirearm",
        camera="sgwr34_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-12,
        max_elevation=44,
    ),
    "sgwr34_france": dict(
        barrel="sgwr34_france_mortarfirearm",
        camera="sgwr34_france_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-12,
        max_elevation=44,
    ),
    "sgwr34_france_ai": dict(
        barrel="sgwr34_france_mortarfirearm",
        camera="sgwr34_france_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-12,
        max_elevation=44,
    ),
    "sgwr34_france_deployed": dict(
        barrel="sgwr34_france_mortarfirearm",
        camera="sgwr34_france_remotecam_holder",
        velocity=185.0,
        gravitymod=4.0,
        elevation_offset=-75.25,
        parabolic=True,
        min_elevation=-12,
        max_elevation=44,
    ),
    "sig33": dict(
        barrel="sig33_gun",
        camera="sig33_remotecam_holder",
        velocity=400.0,
        gravitymod=10.0,
        elevation_offset=-2.833,
        static=True,
        min_elevation=-43.0673,
        max_elevation=4,
    ),
    "stuka_fuzz_rocketpod": dict(
        barrel="stuka_fuzz_rocketpod_rocket",
        camera="sdkfz251d_sf_remotecam_holder",
        velocity=195.0,
        gravitymod=1.8,
        elevation_offset=0.0,
        static=False,
        min_elevation=-40,
        max_elevation=20,
    ),
    "t19_hmc_gunner": dict(
        barrel="t19_hmc_barrel",
        camera="t19_105mm_remotecam_holder",
        velocity=480.0,
        gravitymod=10,
        elevation_offset=-13.75,
        static=False,
        min_elevation=-21,
        max_elevation=16,
    ),
    # "type92_70mm": dict(
    #     barrel="type92_70mm_gun",
    #     camera="type92_70mm_remotecam_holder",
    #     velocity=480.0,
    #     gravitymod=10.0,
    #     elevation_offset=-0.6,
    #     static=True,
    #     min_elevation=-20,
    #     max_elevation=7.5,
    # ),
    
    # "type92_70mm_ai": dict(
    #     barrel="type92_70mm_gun",
    #     camera="type92_70mm_remotecam_holder",
    #     velocity=480.0,
    #     gravitymod=10.0,
    #     elevation_offset=-0.6,
    #     static=True,
    #     min_elevation=-20,
    #     max_elevation=7.5,
    # ),
    "us05insinglemk30_arty": dict(
        barrel="US05inSingleMK30_Arty_GunBarrelBase",
        camera="us05insinglemk30_arty_remotecam_holder",
        velocity=760.0,
        gravitymod=10.0,
        elevation_offset=0.0,
        static=True,
        min_elevation=-24,
        max_elevation=20,
    ),
    "us05insinglemk30_arty_1": dict(
        barrel="US05inSingleMK30_Arty_1_GunBarrelBase",
        camera="us05insinglemk30_arty_1_remotecam_holder",
        velocity=760.0,
        gravitymod=10.0,
        elevation_offset=0.0,
        static=True,
        min_elevation=-24,
        max_elevation=20,
    ),
    "wespe": dict(
        barrel="wespe_gun",
        camera="wespe_remotecam_holder",
        velocity=480.0,
        gravitymod=10.0,
        elevation_offset=-0.85,
        static=False,
        min_elevation=-42,
        max_elevation=5,
    ),
    "willysmb_rocket_codriver": dict(
        barrel="WillysMB_rockets",
        camera="willysmb_rocket_remotecam_holder",
        velocity=150.0,
        gravitymod=2.0,
        elevation_offset=-2.75,
        static=False,
        min_elevation=30,
        max_elevation=3,
    ),
    "wurfgerat41": dict(
        barrel="wurfgerat28_trigger",
        camera="wurfgerat41_remotecam_holder",
        velocity=195.0,
        gravitymod=1.8,
        elevation_offset=-22.0,
        static=True,
        min_elevation=-20,
        max_elevation=15,
    ),
    "zzkatjusha_bm13_gunner": dict(
        barrel="katjusha_bm13_launcher",
        camera="katjusha_remotecam_holder",
        velocity=320.0,
        gravitymod=3.0,
        elevation_offset=-3.68,
        static=False,
        min_elevation=-30,
        max_elevation=0,
    ),
    # "zis3_ind": dict(
    #     barrel="zis3_static_cannon",
    #     camera="Tank_GunnerCamera_lod0",
    #     velocity=427.0,
    #     gravitymod=10.0,
    #     elevation_offset=-0.25,
    #     static=True,
    #     min_elevation=-20,
    #     max_elevation=15,
    # ),
    # "pak40_static": dict(
    #     barrel="pak40_static_HE_Gun",
    #     camera="Tank_GunnerCamera",
    #     velocity=395.0,
    #     gravitymod=10.0,
    #     elevation_offset=-0.25,
    #     static=True,
    #     min_elevation=-20,
    #     max_elevation=15,
    # ),
}

artillery = artillery_info.keys()

# We need this to be able to give spotting points to spotters using
# vehicles, like spotterplanes
# Dict PlayerControlObject -> GenericFireArm
targetting_pcos = {
    "beaufightermk1_rearobserver": "beaufightermk1_rearobserver_gb",
    "mle39_periscope": "mle39_periscope_firearm",
    "pipercub_gb_frontspotter": "piper_front_spotter",
    "pipercub_us_frontspotter": "piper_front_spotter_us",
    "sf14_periscope": "sf14_periscope_firearm",
    "storch_france_rearspotter": "storch_france_spotter",
    "storch_trop_rearspotter": "storch_trop_spotter",
    "stug_lookout": "stug_front_spotter_de",
    "stugr_lookout": "stug40r_front_spotter_de",
    "tiger_p_lookout": "stug_front_spotter_de",
}

deployables = {
    "81krh36_dep": dict(
        template="81krh36_deployed",
        offset=0.03,
        flatten=True,
    ),
    "3inchmortar_dep": dict(
        template="3inchmortar_deployed",
        offset=0.11,
        flatten=True,
    ),
    "81mm_mortar_dep": dict(
        template="81mm_mortar_m1_deployed",
        offset=0.03,
        flatten=True,
    ),
    "81mm_mortar_fr_2730_dep": dict(
        template="81mm_mortar_fr_2730_deployed",
        offset=0.03,
        flatten=True,
    ),
    "81mm_mortar_no_m35_dep": dict(
        template="81mm_mortar_no_m35_deployed",
        offset=0.03,
        flatten=True,
    ),
    "bredam37_dep": dict(
        template="bredam37_tripod_dep",
        offset=0.07,
    ),
    "hotchkiss1914_dep": dict(
        template="hotchkiss1914_deployed",
        offset=0.15,
        flatten=True,
    ),
    "m29_tripod_dep": dict(
        template="m29_tripod_deployed",
        offset=-0.43,
        flatten=True,
    ),
    "m29_tripod_scope_dep": dict(
        template="m29_tripod_scope_deployed",
        offset=-0.43,
        flatten=True,
    ),
    "m1917a1_dep": dict(
        template="m1917_tripod_deployed",
        offset=0.1,
        flatten=True,
    ),
    "m1919a4_dep": dict(
        template="m1919a4",
        offset=0.24,
    ),
    "mg34_lafette_dep": dict(
        template="mg34_lafette_deployed",
        offset=0.3,
        flatten=True,
    ),
    "mg34_lafettemgz34_dep": dict(
        template="mg34_lafettemgz34_deployed",
        offset=0.3,
        flatten=True,
    ),
    "mg42_lafette_dep": dict(
        template="mg42_lafette_deployed",
        offset=0.16,
        flatten=True,
    ),
    "mg42_lafettemgz34_dep": dict(
        template="mg42_lafettemgz34_deployed",
        offset=0.16,
        flatten=True,
    ),
    "ru_mortar82mm_dep": dict(
        template="ru_mortar82mm_deployed",
        offset=0.01,
        flatten=True,
    ),
    "sgwr34_dep": dict(
        template="sgwr34_deployed",
        offset=0.08,
        flatten=True,
    ),
    "sgwr34_france_dep": dict(
        template="sgwr34_france_deployed",
        offset=0.08,
        flatten=True,
    ),
    "vickers303_dep": dict(
        template="vickers303_tripod_dep",
        offset=0.03,
        flatten=True,
    ),
    "wz30_tripod_dep": dict(
        template="wz30_tripod_deployed",
        offset=-0.02,
        flatten=True,
    ),
}

portee_info = {
    "bedford_qlt_6pdr": dict(
        gun_spawner="bedford_6pdrspawner",
        gun="6pdr_mkiv_bedford_qlt",
        inc_path=(
            "/Objects/Vehicles/Land/GB" "/Bedford_QLT/bedford_6pdrspawner.inc"
        ),
    ),
    "fiat626_47mm": dict(
        gun_spawner="fiat626_cannonespawner",
        gun="cannone_da_47_32_fiat626",
        inc_path=(
            "/Objects/Vehicles/Land/IT" "/fiat626/fiat626_cannonespawner.inc"
        ),
    ),
    "sdkfz7_pak": dict(
        gun_spawner="sdkfz7_pak40_spawner",
        gun="pak40_sdkfz7",
        inc_path=(
            "/Objects/Vehicles/Land/DE/" "/sdkfz7/sdkfz7_pak/pak40_spawner.inc"
        ),
    ),
    "sdkfz7_pak40": dict(
        gun_spawner="pak40_towed_spawner",
        gun="pak40_towed",
        inc_path=(
            "/Objects/Vehicles/Land/DE"
            "/sdkfz7/sdkfz7_pak40/pak40_towed_spawner.inc"
        ),
    ),
    "sdkfz7_pak_camo": dict(
        gun_spawner="sdkfz7_camo_pak38_spawner",
        gun="pak38_sdkfz7_camo",
        inc_path=(
            "/Objects/Vehicles/Land/DE"
            "/sdkfz7/sdkfz7_pak/pak38_fr_spawner.inc"
        ),
    ),
    "sdkfz7_pak_camo_2": dict(
        gun_spawner="sdkfz7_camo_pak38_spawner_2",
        gun="pak38_sdkfz7_camo_2",
        inc_path=(
            "/Objects/Vehicles/Land/DE"
            "/sdkfz7/sdkfz7_pak/pak38_fr_spawner_2.inc"
        ),
    ),
    "sdkfz7_pak_dak": dict(
        gun_spawner="sdkfz7_dak_pak38_spawner",
        gun="pak38_sdkfz7_dak",
        inc_path=(
            "/Objects/Vehicles/Land/DE" "/sdkfz7/sdkfz7_pak/pak38_spawner.inc"
        ),
    ),
    "sdkfz7_pak_dak_2": dict(
        gun_spawner="sdkfz7_dak_pak38_spawner_2",
        gun="pak38_sdkfz7_dak_2",
        inc_path=(
            "/Objects/Vehicles/Land/DE"
            "/sdkfz7/sdkfz7_pak/pak38_spawner_2.inc"
        ),
    ),
    "sdkfz7_pak_dak_3": dict(
        gun_spawner="sdkfz7_dak_pak38_spawner_3",
        gun="pak38_sdkfz7_dak_3",
        inc_path=(
            "/Objects/Vehicles/Land/DE"
            "/sdkfz7/sdkfz7_pak/pak38_spawner_3.inc"
        ),
    ),
}
