# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("conq_16_courtyard_1", 201),
  spawnPoint("conq_16_courtyard_2", 201),
  spawnPoint("conq_16_courtyard_3", 201),
  spawnPoint("conq_16_courtyard_4", 201),
  spawnPoint("conq_16_fort_1", 202),
  spawnPoint("conq_16_fort_2", 202),
  spawnPoint("conq_16_fort_3", 202),
  spawnPoint("conq_16_fort_4", 202),
  spawnPoint("conq_16_station_1_0", 203),
  spawnPoint("conq_16_station_2_0", 203),
  spawnPoint("conq_16_station_3_0", 203),
  spawnPoint("conq_16_station_4_0", 203),
]
