# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_32_sme_82abn_1_0", 201, group = 1),
  spawnPoint("CP_32_sme_82abn_2_0", 201, group = 1),
  spawnPoint("CP_32_sme_to_carentan_0_2", 203),
  spawnPoint("CP_32_sme_to_carentan_0_3", 203),
  spawnPoint("CP_32_sme_to_carentan_1", 203),
  spawnPoint("CP_32_sme_faubourg_2_0", 204),
  spawnPoint("CP_32_sme_faubourg_3_0", 204),
  spawnPoint("CP_32_sme_faubourg_1_0", 204),
  spawnPoint("CP_32_sme_centre_ville_0_2", 205),
  spawnPoint("CP_32_sme_centre_ville_0_3", 205),
  spawnPoint("CP_32_sme_centre_ville_1", 205),
  spawnPoint("CP_32_sme_to_utah_beach_2_0", 207),
  spawnPoint("CP_32_sme_to_utah_beach_3_0", 207),
  spawnPoint("CP_32_sme_to_utah_beach_1_0", 207),
  spawnPoint("CP_32_sme_old_hospital_2_0", 208),
  spawnPoint("CP_32_sme_old_hospital_3_0", 208),
  spawnPoint("CP_32_sme_old_hospital_1_0", 208),
  spawnPoint("CP_32_sme_82abn_3_0", 201, group = 1),
  spawnPoint("CP_32_sme_82abn_4_0", 201, group = 1),
]
