# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_sme_82abn_1_0", 1),
  spawnPoint("CP_16_sme_82abn_2_0", 1),
  spawnPoint("CP_16_sme_ferme_2_0", 101),
  spawnPoint("CP_16_sme_ferme_3_0", 101),
  spawnPoint("CP_16_sme_ferme_1_0", 101),
  spawnPoint("CP_16_sme_eglise_0_2", 102),
  spawnPoint("CP_16_sme_eglise_0_3", 102),
  spawnPoint("CP_16_sme_eglise_1", 102),
  spawnPoint("CP_16_sme_control_post_0_2", 103),
  spawnPoint("CP_16_sme_control_post_0_3", 103),
  spawnPoint("CP_16_sme_control_post_1", 103),
  spawnPoint("CP_16_sme_la_fabrique_0_2", 104),
  spawnPoint("CP_16_sme_la_fabrique_0_3", 104),
  spawnPoint("CP_16_sme_la_fabrique_1", 104),
  spawnPoint("CP_16_sme_82abn_3_0", 1),
  spawnPoint("CP_16_sme_82abn_4_0", 1),
  spawnPoint("CP_16_sme_82abn_5", 1),
]
