# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_lenino_lenino_1_1", 3),
  spawnPoint("CP_16_lenino_lenino_2_1", 3),
  spawnPoint("CP_16_lenino_lenino_3_1", 3),
  spawnPoint("CP_16_lenino_lenino_0", 3),
  spawnPoint("CP_16_lenino_lenino_0_0", 3),
  spawnPoint("CP_16_lenino_lenino_6", 3),
  spawnPoint("CP_16_lenino_trigubova_1", 1),
  spawnPoint("CP_16_lenino_trigubova_2", 1),
  spawnPoint("CP_16_lenino_trigubova_3", 1),
  spawnPoint("CP_16_lenino_trigubova_4", 1),
  spawnPoint("CP_16_lenino_trigubova_5", 1),
  spawnPoint("CP_16_lenino_trigubova_6", 1),
]
