# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_arad_westvillage_1_1", 10),
  spawnPoint("CP_16_arad_westvillage_2", 10),
  spawnPoint("CP_16_arad_westvillage_3", 10),
  spawnPoint("CP_16_arad_westvillage_4", 10),
  spawnPoint("CP_16_arad_westvillage_5", 10),
  spawnPoint("CP_16_Arad_EastVillage_4", 11),
  spawnPoint("CP_16_Arad_EastVillage_5", 11),
  spawnPoint("CP_16_Arad_EastVillage_6", 11),
  spawnPoint("CP_16_arad_crashsite_1_0", 12),
  spawnPoint("CP_16_arad_crashsite_2_0", 12),
  spawnPoint("CP_16_arad_crashsite_4_0", 12),
  spawnPoint("CP_16_arad_crashsite_5_0", 12),
  spawnPoint("CP_16_Arad_EastVillage_7", 11),
  spawnPoint("CP_16_Arad_EastVillage_8", 11),
  spawnPoint("CP_16_arad_crashsite_5", 12),
  spawnPoint("CP_16_arad_westvillage_6", 10),
]
