# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("german_main_1", 108),
  spawnPoint("german_main_2", 108),
  spawnPoint("german_main_3", 108),
  spawnPoint("german_main_4", 108),
  spawnPoint("german_main_5", 108),
  spawnPoint("german_main_6", 108),
  spawnPoint("german_main_7", 108),
  spawnPoint("german_main_8", 108),
  spawnPoint("us_main_1", 106),
  spawnPoint("us_main_2", 106),
  spawnPoint("us_main_3", 106),
  spawnPoint("us_main_4", 106),
  spawnPoint("us_main_5", 106),
  spawnPoint("us_main_6", 106),
  spawnPoint("us_main_7", 106),
  spawnPoint("us_main_8", 106),
]
