# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_STLO_Farmhouse_1", 302),
  spawnPoint("CP_16_STLO_Farmhouse_2", 302),
  spawnPoint("CP_16_STLO_Farmhouse_3", 302),
  spawnPoint("CP_16_STLO_Farmhouse_4", 302),
  spawnPoint("CP_16_STLO_Les_Foulons_1", 305),
  spawnPoint("CP_16_STLO_Les_Foulons_2", 305),
  spawnPoint("CP_16_STLO_Les_Foulons_3", 305),
  spawnPoint("CP_16_STLO_Les_Foulons_4", 305),
  spawnPoint("CP_16_STLO_Market_1", 301),
  spawnPoint("CP_16_STLO_Market_2", 301),
  spawnPoint("CP_16_STLO_Market_3", 301),
  spawnPoint("CP_16_STLO_Market_4", 301),
  spawnPoint("CP_16_STLO_Villiers_Fossard_1", 303),
  spawnPoint("CP_16_STLO_Villiers_Fossard_2", 303),
  spawnPoint("CP_16_STLO_Villiers_Fossard_3", 303),
  spawnPoint("CP_16_STLO_Villiers_Fossard_4", 303),
]
