# usernames/squadnames that get you autokicked
words = [
  # generic racism
    "rhodesia",
    "nigger",
    "negro",
    "mosley",
  # generic nazi
    "reich",
    "jugend",  # HJ
    "sieg heil",
    "siegheil",
    "sturmabteilung",
    "schutzstaffel",
    "reichenau",
    "ribbentrop",
    "rosenberg",
    "rudolf hess",
    "1488",
    "adolf",
    "ahnenerbe",
    "aryan",
    "endsieg",
    "fuehrer",
    "fuhrer",
    "bormann",
    "gestapo",
    "goebbels",
    "goering",
    "goring",
    "heydrich",
    "hilter",
    "himler",
    "himmler",
    "hitler",
    "hoess",
    "hoss",
    "jodl",
    "kaltenbrunner",
  # holocaust
    "einsatz",
    "auschwitz",
    "belzec",
    "buchenwald",
    "chelmno",
    "dachau",
    "eichmann",
    "endloesung",
    "endlosung",
    "judenrein",
    "judensau",
    "judenschwein",
    "juden",
    "majdanek",
    "mauthausen",
    "mengele",
    "sachsenhausen",
    "sobibor",
    "treblinka",
    "zyklon",
    "dirlewanger",
    # wehraboos
    "waffen_ss",
    "waffenss",
    "wehrwolf",
    "wherewolf",
    "werwolf",
    "volkssturm",
    "volksturm",
    "lssah",
    "leibstand",
    "leibstandarte",
    "germania",
    "totenkopf",
    "wiking",
    "westland",
    "ostland",
    "nordland",
    "hohenstaufen",
    "frundsberg",
    "handschar",
    "skanderbeg",
    "theresia",
    "karstjager",
    "hunyadi",
    "langemarck",
    "sturmbrigad",
    "sturmbatal",
    "sturmbattal",
    "wessel",
    "wallonien",
    "wotan",
    "berliching",
    "ostlegion",
    "charlemagne",
    "landstorm",
    "nibelung",
    "mohnke",
    # Russian obscenities
    "pidor",
    "pidar",
    "pidoras",
    "pedik",
    "pedrila",
    "huesos",
    "khuesos",
    "mudak",
    "gandon",
    "gondon",
    "huilo",
    "huylo",
    "eblan",
    "cyka",
    "suka",
    "dolboeb",
    "dolbaeb",
    "govnoed",
    "pizdyuk",
    "pizduk",
]

# if this is the ENTIRE name
# cant check like "if 'ss' is in name"
phrases = [
"ss"
]
