# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_Crete1941_Chania_9", 302),
  spawnPoint("CP_16_Crete1941_Chania_10", 302),
  spawnPoint("CP_16_Crete1941_Chania_1", 302),
  spawnPoint("CP_16_Crete1941_Chania_2", 302),
  spawnPoint("CP_16_Crete1941_Chania_3", 302),
  spawnPoint("CP_16_Crete1941_Chania_6", 302),
  spawnPoint("CP_16_Crete1941_Chania_7", 302),
  spawnPoint("CP_16_Crete1941_Chania_8", 302),
  spawnPoint("CP_16_Crete1941_Monastery_Odigitrias_0", 303),
  spawnPoint("CP_16_Crete1941_Monastery_Odigitrias_0_0", 303),
  spawnPoint("CP_16_Crete1941_Monastery_Odigitrias_1", 303),
  spawnPoint("CP_16_Crete1941_Monastery_Odigitrias_2", 303),
  spawnPoint("CP_16_Crete1941_Monastery_Odigitrias_3", 303),
  spawnPoint("CP_16_Crete1941_Olive_axis1", 301),
  spawnPoint("CP_16_Crete1941_Olive_axis2", 301),
  spawnPoint("CP_16_Crete1941_Olive_axis3", 301),
  spawnPoint("CP_16_Crete1941_Olive_allies1", 301),
  spawnPoint("CP_16_Crete1941_Olive_allies2", 301),
  spawnPoint("CP_16_Crete1941_Olive_allies3", 301),
]
