# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_SP_Crete1941_Suda_Bay_0", 301),
  spawnPoint("CP_16_SP_Crete1941_Suda_Bay_0_0", 301),
  spawnPoint("CP_16_SP_Crete1941_Suda_Bay_1", 301, human_only = True),
  spawnPoint("CP_16_SP_Crete1941_Suda_Bay_3", 301, human_only = True),
  spawnPoint("CP_16_SP_Crete1941_Suda_Bay_4", 301, human_only = True),
  spawnPoint("CP_16_SP_Crete1941_Suda_Bay_5", 301),
  spawnPoint("CP_16_SP_Crete1941_Chania_0", 302),
  spawnPoint("CP_16_SP_Crete1941_Chania_0_0", 302),
  spawnPoint("CP_16_SP_Crete1941_Chania_1", 302),
  spawnPoint("CP_16_SP_Crete1941_Chania_2", 302),
  spawnPoint("CP_16_SP_Crete1941_Chania_3", 302),
  spawnPoint("CP_16_SP_Crete1941_Chania_6", 302),
  spawnPoint("CP_16_SP_Crete1941_Chania_7", 302, human_only = True),
  spawnPoint("CP_16_SP_Crete1941_Chania_8", 302),
  spawnPoint("CP_16_SP_Crete1941_Monastery_Odigitrias_0", 303),
  spawnPoint("CP_16_SP_Crete1941_Monastery_Odigitrias_0_0", 303),
  spawnPoint("CP_16_SP_Crete1941_Monastery_Odigitrias_1", 303),
  spawnPoint("CP_16_SP_Crete1941_Monastery_Odigitrias_2", 303),
  spawnPoint("CP_16_SP_Crete1941_Monastery_Odigitrias_3", 303),
]
