# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("cp_16_la_hardt_1re_armee_fr_1", 304),
  spawnPoint("cp_16_la_hardt_1re_armee_fr_2", 304),
  spawnPoint("cp_16_la_hardt_1re_armee_fr_3", 304),
  spawnPoint("cp_16_la_hardt_1re_armee_fr_4", 304),
  spawnPoint("cp_16_la_hardt_1re_armee_fr_5", 304),
  spawnPoint("cp_16_la_hardt_1re_armee_fr_6", 304),
  spawnPoint("cp_16_xix_armee_1", 2),
  spawnPoint("cp_16_xix_armee_2", 2),
  spawnPoint("cp_16_xix_armee_3", 2),
  spawnPoint("cp_16_xix_armee_4", 2),
  spawnPoint("cp_16_xix_armee_5", 2),
  spawnPoint("cp_16_xix_armee_6", 2),
  spawnPoint("cp_16_la_hardt_1re_armee_fr_7", 304),
  spawnPoint("cp_16_xix_armee_7", 2),
]
