# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_MM_East_Matruh_1", 204),
  spawnPoint("CP_16_MM_East_Matruh_2", 204),
  spawnPoint("CP_16_MM_East_Matruh_3", 204),
  spawnPoint("CP_16_MM_East_Matruh_4", 204),
  spawnPoint("CP_16_MM_Matruh_HQ_1", 203),
  spawnPoint("CP_16_MM_Matruh_HQ_2", 203),
  spawnPoint("CP_16_MM_Matruh_HQ_3", 203),
  spawnPoint("CP_16_MM_Matruh_HQ_4", 203),
  spawnPoint("CP_16_MM_Mosquee_1", 202),
  spawnPoint("CP_16_MM_Mosquee_2", 202),
  spawnPoint("CP_16_MM_Mosquee_3", 202),
  spawnPoint("CP_16_MM_West_Matruh_1", 201),
  spawnPoint("CP_16_MM_West_Matruh_2", 201),
  spawnPoint("CP_16_MM_West_Matruh_3", 201),
  spawnPoint("CP_16_MM_West_Matruh_4", 201),
  spawnPoint("CP_16_MM_West_Matruh_5", 201),
  spawnPoint("CP_16_MM_East_Matruh_5", 204),
  spawnPoint("CP_16_MM_Mosquee_4", 202),
]
