# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_SP_Supercharge_Ghazal_1", 202),
  spawnPoint("CP_16_SP_Supercharge_Ghazal_2", 202),
  spawnPoint("CP_16_SP_Supercharge_Ghazal_3", 202),
  spawnPoint("CP_16_SP_Supercharge_Ghazal_4", 202),
  spawnPoint("CP_16_SP_Supercharge_El_Daba_1", 201),
  spawnPoint("CP_16_SP_Supercharge_El_Daba_2", 201),
  spawnPoint("CP_16_SP_Supercharge_El_Daba_3", 201),
  spawnPoint("CP_16_SP_Supercharge_El_Daba_4", 201),
  spawnPoint("CP_16_SP_Supercharge_East_El_Daba_1", 203, human_only = True),
  spawnPoint("CP_16_SP_Supercharge_East_El_Daba_2", 203),
  spawnPoint("CP_16_SP_Supercharge_East_El_Daba_3", 203),
  spawnPoint("CP_16_SP_Supercharge_East_El_Daba_4", 203, human_only = True),
]
