# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CP_16_tunis_gb_1", 202),
  spawnPoint("CP_16_tunis_de_1", 201),
  spawnPoint("CP_16_tunis_gb_2", 202),
  spawnPoint("CP_16_tunis_gb_3", 202),
  spawnPoint("CP_16_tunis_gb_4", 202),
  spawnPoint("CP_16_tunis_gb_5", 202),
  spawnPoint("CP_16_tunis_gb_6", 202),
  spawnPoint("CP_16_tunis_de_2", 201),
  spawnPoint("CP_16_tunis_de_3", 201),
  spawnPoint("CP_16_tunis_de_4", 201),
]
