# Generated by python.packing.fh2pack_maps. Do not alter by hand.
from game.plugins.teamSPs import spawnPoint
spawnpoints = [
  spawnPoint("CQ_16_EPPEL_US_1", 302),
  spawnPoint("CQ_16_EPPEL_DE_1", 303),
  spawnPoint("CQ_16_EPPEL_US_2", 302),
  spawnPoint("CQ_16_EPPEL_US_3", 302),
  spawnPoint("CQ_16_EPPEL_US_4", 302),
  spawnPoint("CQ_16_EPPEL_US_5", 302),
  spawnPoint("CQ_16_EPPEL_DE_2", 303),
  spawnPoint("CQ_16_EPPEL_DE_3", 303),
  spawnPoint("CQ_16_EPPEL_DE_4", 303),
  spawnPoint("CQ_16_EPPEL_DE_5", 303),
  spawnPoint("CQ_16_EPPEL_DE_6", 303),
  spawnPoint("CQ_16_EPPEL_US_6", 302),
]
